export const SET_INGREDIENT_FOR_CONSTRUCTOR = 'SET_INGREDIENT_FOR_CONSTRUCTOR';
export const DELETE_INGREDIENT_FOR_CONSTRUCTOR = 'DELETE_INGREDIENT_FOR_CONSTRUCTOR';
export const SET_TOTAL_PRICE = 'SET_TOTAL_PRICE';
export const MOVE_INGREDIENT = 'MOVE_INGREDIENT';
