export const WS_CONNECTION_START_AUTH_USER = 'WS_CONNECTION_START_AUTH_USER';
export const WS_AUTH_CONNECTION_SUCCESS = 'WS_AUTH_CONNECTION_SUCCESS';
export const WS_AUTH_CONNECTION_ERROR = 'WS_AUTH_CONNECTION_ERROR';
export const WS_AUTH_CONNECTION_CLOSED = 'WS_AUTH_CONNECTION_CLOSED';
export const WS_AUTH_GET_MESSAGE = 'WS_AUTH_GET_MESSAGE';
export const WS_AUTH_SEND_MESSAGE = 'WS_AUTH_SEND_MESSAGE';
export const WS_AUTH_CLOSE_CONNECTION_BY_USER_SIDE = 'WS_AUTH_CLOSE_CONNECTION_BY_USER_SIDE';
