export const WS_CONNECTION_START_UNAUTH_USER = 'WS_CONNECTION_START_UNAUTH_USER';
export const WS_CONNECTION_START_AUTH_USER = 'WS_CONNECTION_START_AUTH_USER';
export const WS_CONNECTION_SUCCESS = 'WS_CONNECTION_SUCCESS';
export const WS_CONNECTION_ERROR = 'WS_CONNECTION_ERROR';
export const WS_CONNECTION_CLOSED = 'WS_CONNECTION_CLOSED';
export const WS_GET_MESSAGE = 'WS_GET_MESSAGE';
export const WS_SEND_MESSAGE = 'WS_SEND_MESSAGE';
export const WS_CLOSE_CONNECTION_BY_USER_SIDE = 'WS_CLOSE_CONNECTION_BY_USER_SIDE';
